### ISSUE TITLE
Add a notification/name color to a player's display name above their head for /pvptoggle:

### ISSUE THREAD

**Issue by otherwise777** [mc-skyprison/SkyPrison#1]
The idea is that when a donor uses /pvptoggle to disable their pvp that their display name above their head will change to a color like blue, for example, which symbolizes to players around them that they are protected.

Then, if that player type /pvptoggle again to re-enable pvp their name goes back to it's original color (white) and they can be attacked.

**Comment by otherwise777** [comment]
We need to think of a proper way to do this without confusing the players, for example some people already have a blue name, and keep in mind the character limit in names

**Comment by blueberry09** [comment]
We could use the &4 red for the display name above their head instead then since we don't allow users to use that color.

**Comment by DrakePork** [comment]
Donzo

**Comment by otherwise777** [comment]
nice
